---
- hosts: prod
  remote_user: root
  become: yes
  become_user: root
  tasks:
   - name: copy the patch script
     copy: src="ospatch_13042022.sh" dest="/tmp"
   - name: set permissions
     file: path=/tmp/script1.sh owner=root group=root mode=0755 state=touch
   - name: execute the script
     shell: /bin/bash /tmp/script1.sh
   - name: reboot the host
     shell: /sbin/reboot
